### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by mccraveiro** [enieber/re-newsletter#2]
Hi! 

Where can I signup for the newsletter?

**Comment by enieber** [comment]
In this moment is open the process to get links. no has signup for send mail, but all suggestion to use and send mails is wellcome.

**Comment by enieber** [comment]
@mccraveiro to receive this newsletter open instructions updated in [Signup in Readme](https://github.com/enieber/re-newsletter/blob/main/README.md#signup), thanks to help this project.
